name: github cd for firebase

on:
  push:
    branches:
    - master
    - release/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
     -name: Trigger deploy in firebas
       env:
            CI: false
       with:
        node-version: '16.17.1'
     - run: npm install
     - run: npm run build --prod
     - uses: w9jds/firebase-action@master
       with:
         args: deploy --only hosting
       env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
